# informer architecture hyperparams
dropout_rate: 0.2
num_encoder_layers: 11
num_decoder_layers: 7
d_model: 128

# data hyperparams
prediction_length: 10
context_length: 20
lags: 
  - 0
freq: "1M"
time_features:
  - "month_of_year"

# training hyperparams
batch_size: 32
num_batches_per_epoch: 1000
weight_decay: 5e-3
lr: 5e-4
