categorical: false
heatmaps_donefile: /global/cscratch1/sd/helenqu/redshift_prediction/sdss/real/all_heatmaps/done.txt
output_path: /pscratch/sd/h/helenqu/plasticc/gp_interp
init_env: source activate tf-2.4.1-cpu
lcdata_paths:
- /pscratch/sd/h/helenqu/plasticc/plasticc_train_lightcurves.csv.gz
metadata_paths:
- /pscratch/sd/h/helenqu/plasticc/plasticc_train_metadata.csv.gz
mode: train
num_epochs: 400
sbatch_header_path: /global/homes/h/helenqu/redshift_prediction/heatmaps_sbatch_header.sh
sn_type_id_to_name:
  0: SNII
  5: SNII
  101: SNII
  102: SNII
  103: SNII
  104: SNII
  105: SNII
  106: SNIa
  110: SNII
  111: SNII
  112: SNII
  113: SNII
  114: SNII
  115: SNII
  118: SNIa
  119: SNIa
  120: SNIa
types:
- SNII
- SNIa
